/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#2696fe",
        primary: "#004e9f",
        "surface-dim": "#d9dadc",
        "error-container": "#ffdad6",
        "tertiary-container": "#af4900",
        "surface-container-highest": "#e2e2e4",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb692",
        "on-tertiary-fixed": "#341100",
        surface: "#f9f9fb",
        "secondary-fixed": "#d3e3ff",
        "on-primary-fixed-variant": "#00458e",
        secondary: "#0060aa",
        "surface-container-high": "#e8e8ea",
        "on-secondary-container": "#002d55",
        "on-primary-fixed": "#001b3e",
        background: "#f9f9fb",
        tertiary: "#883700",
        "on-primary-container": "#dfe8ff",
        "inverse-surface": "#2f3132",
        "surface-variant": "#e2e2e4",
        "on-surface-variant": "#414753",
        "inverse-primary": "#aac7ff",
        "on-tertiary-fixed-variant": "#793000",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#aac7ff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#a3c9ff",
        outline: "#727784",
        "on-secondary-fixed-variant": "#004882",
        "on-background": "#1a1c1d",
        "inverse-on-surface": "#f0f0f2",
        "outline-variant": "#c1c6d5",
        "surface-container": "#eeeef0",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-container": "#ffe3d6",
        "primary-container": "#0066cc",
        "surface-container-low": "#f3f3f5",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001c39",
        "on-surface": "#1a1c1d",
        "primary-fixed": "#d7e3ff",
        "surface-tint": "#005cba",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9fb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "space-xxs": "4px",
        "space-lg": "24px",
        "space-xxl": "48px",
        "space-md": "17px",
        "space-section": "80px",
        "space-sm": "12px",
        "space-xs": "8px",
        "space-xl": "32px",
        margin: "32px",
      },
      fontFamily: {
        "button-utility": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        tagline: ['"SF Pro Display"', 'Inter', 'system-ui', 'sans-serif'],
        "display-md": ['"SF Pro Display"', 'Inter', 'system-ui', 'sans-serif'],
        "caption-strong": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "fine-print": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "dense-link": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "micro-legal": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "body-strong": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "hero-display": ['"SF Pro Display"', 'Inter', 'system-ui', 'sans-serif'],
        lead: ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        body: ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "display-lg": ['"SF Pro Display"', 'Inter', 'system-ui', 'sans-serif'],
        caption: ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "lead-airy": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "button-large": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
        "nav-link": ['"SF Pro Text"', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        "button-utility": ["14px", { lineHeight: "1.29", letterSpacing: "-0.224px", fontWeight: "400" }],
        tagline: ["21px", { lineHeight: "1.19", letterSpacing: "0.231px", fontWeight: "600" }],
        "display-md": ["34px", { lineHeight: "1.47", letterSpacing: "-0.374px", fontWeight: "600" }],
        "caption-strong": ["14px", { lineHeight: "1.29", letterSpacing: "-0.224px", fontWeight: "600" }],
        "fine-print": ["12px", { lineHeight: "1.0", letterSpacing: "-0.12px", fontWeight: "400" }],
        "dense-link": ["17px", { lineHeight: "2.41", letterSpacing: "0px", fontWeight: "400" }],
        "micro-legal": ["10px", { lineHeight: "1.3", letterSpacing: "-0.08px", fontWeight: "400" }],
        "body-strong": ["17px", { lineHeight: "1.24", letterSpacing: "-0.374px", fontWeight: "600" }],
        "hero-display": ["56px", { lineHeight: "1.07", letterSpacing: "-0.28px", fontWeight: "600" }],
        lead: ["28px", { lineHeight: "1.14", letterSpacing: "0.196px", fontWeight: "400" }],
        body: ["17px", { lineHeight: "1.47", letterSpacing: "-0.374px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "1.10", letterSpacing: "0px", fontWeight: "600" }],
        caption: ["14px", { lineHeight: "1.43", letterSpacing: "-0.224px", fontWeight: "400" }],
        "lead-airy": ["24px", { lineHeight: "1.5", letterSpacing: "0px", fontWeight: "300" }],
        "button-large": ["18px", { lineHeight: "1.0", letterSpacing: "0px", fontWeight: "300" }],
        "nav-link": ["12px", { lineHeight: "1.0", letterSpacing: "-0.12px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
